services:
  clusterizer-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: clusterizer-backend
    command: sh -c "uvicorn web_app.main:app --host 0.0.0.0 --port 8080 --workers 1"
    volumes:
      - ./backend:/home/app/web
    ports:
      - "8080:8080"
    env_file:
      - .env
  clusterizer-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: clusterizer-frontend
    command: sh -c "npm run dev -- --host"
    volumes:
      - ./frontend:/home/app/web
    ports:
      - "5173:5173"
    env_file:
      - .env
  clusterizer-database:
    image: 'postgres:17.2'
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  pgdata: